#!/bin/bash

user_dir=$HOME/.odpscmd
sys_dir=/opt/odpscmd/conf

if [ ! -e ${user_dir} ]; then
    if [ ! -d ${user_dir} ]; then
        echo "init $HOME/.odpscmd/odps_config.ini ..."
        mkdir -p ${user_dir}
        cp ${sys_dir}/odps_config.ini ${user_dir}/odps_config.ini
    fi
fi

function lowest_unused_fd() {
    local FD=10
    while [ -e /dev/fd/$FD ]; do
        FD=$((FD+1))
    done
    echo $FD
}

file=`mktemp -t "XXXXXXXX"`

wfd=$(lowest_unused_fd)
eval "exec $wfd>$file"

rfd=$(lowest_unused_fd)
eval "exec $rfd<$file"
rm -f $file

for var in "$@"
do
    printf -- "%s\0" "$var" >&$wfd
done

eval "exec $wfd>&-"

java -Xms64m -Xmx512m -classpath "/opt/odpscmd/lib/*:${user_dir}/:${sys_dir}/" com.aliyun.openservices.odps.console.ODPSConsole  -I $rfd
